# Usar una versión específica de la imagen de PostgreSQL
FROM postgres:16-alpine3.17

# Establecer el directorio de trabajo
WORKDIR /usr/src/app

# Copiar el archivo .env al contenedor
COPY .env ./

# Cambiar el propietario y los permisos del archivo .env para que el usuario postgres pueda acceder a él
RUN chown postgres:postgres .env && \
    chmod 600 .env
