# Dockerfile para la imagen de la base de datos PostgreSQL

FROM postgres:16-alpine3.17

# Copiar el archivo .env al contenedor y cargar las variables de entorno
COPY .env /usr/src/app/.env

# Establecer variables de entorno para la base de datos
ENV POSTGRES_DB=$DB_NAME
ENV POSTGRES_USER=$DB_USER
ENV POSTGRES_PASSWORD=$DB_PASSWORD
