name: DockerHub

on:
  workflow_run:
    workflows: ["SonarCloud CI"]
    types:
      - completed

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Descarga el archivo de estado compartido desde el flujo de trabajo anterior
      - name: Download completion flag
        uses: actions/download-artifact@v2
        with:
          name: analysis-completed
          path: .

      # Comprueba si el archivo de estado existe
      - name: Verify completion flag
        run: |
          if [ ! -f analysis_completed.txt ]; then
            echo "SonarCloud analysis not completed. Exiting..."
            exit 1
          fi

      # Tus pasos para construir y publicar imágenes Docker aquí...
