name: SonarCloud

on:
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Inicializar contenedores
      - name: Start containers
        run: docker-compose -f docker-compose.yml up --build -d

      # Esperar a que los contenedores estén listos (ajustar según sea necesario)
      - name: Wait for containers to be ready
        run: docker-compose -f docker-compose.yml exec -T db sh -c 'while !</dev/tcp/db/5432; do sleep 1; done;'

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Ejecutar pruebas y cobertura
      - name: Run tests and coverage
        run: |
          pip install coverage
          coverage run --source='.' manage.py test

      # Escanear con SonarCloud
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
