name: SonarCloud

on:
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:16-alpine3.17
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432

      web:
        image: python:3.9
        ports:
          - 8000:8000

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Docker Compose
        run: |
          docker-compose up -d
          docker-compose exec -T db sh -c 'while !</dev/tcp/db/5432; do sleep 1; done;'

      # Ejecutar pruebas y cobertura
      - name: Run tests and coverage
        run: |
          pip install coverage
          docker-compose exec web coverage run --source='.' manage.py test

      # Escanear con SonarCloud
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
