name: SonarCloud

on:
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker images
        run: docker-compose build

      - name: Start Docker Compose
        run: |
          docker-compose up -d
          docker-compose exec -T db sh -c 'while !</dev/tcp/db/5432; do sleep 1; done;'

      - name: Wait for web service to be ready
        run: |
          sleep 20  # Esperar 20 segundos para asegurar que el servicio web esté listo

      - name: Run tests and coverage
        run: |
          pip install coverage
          docker-compose exec web coverage run --source='.' manage.py test

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
