name: SonarCloud

on:
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_DB: ${DB_NAME}
          POSTGRES_USER: ${DB_USER}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
          - 5432:5432

      pgadmin:
        image: ervincaravaliibarra/pgadmin-galeria-6:latest
        ports:
          - 90:80

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Configurar otros servicios si son necesarios

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage

      - name: Run tests
        run: |
          docker-compose build tests
          docker-compose run tests

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ./coverage.xml

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
