name: SonarCloud

on:
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Compose
        uses: docker/compose-action@v2
        with:
          compose-file: docker-compose.yml

      - name: Start Docker services
        run: docker-compose up -d

      - name: Wait for services to be ready
        run: |
          docker-compose exec web sh -c "python manage.py check"
          docker-compose exec db sh -c "pg_isready -h localhost -U postgres"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage pytest

      - name: Run tests with coverage and generate report
        run: |
          docker-compose exec web sh -c "coverage run --source=. -m pytest -rs"
          docker-compose exec web sh -c "mkdir -p coverage-reports"
          docker-compose exec web sh -c "coverage xml -o coverage-reports/coverage.xml"

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
