name: SonarCloud CI

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Tus pasos para pruebas y análisis aquí...

      - name: Set flag indicating completion
        run: echo "SonarCloud analysis completed" > analysis_completed.txt
        # Guarda el archivo de estado como un artefacto
        # para que el siguiente flujo de trabajo pueda acceder a él.
        # Esto lo hace disponible para el siguiente flujo de trabajo.
        - name: Upload completion flag
          uses: actions/upload-artifact@v2
          with:
            name: analysis-completed
            path: analysis_completed.txt
