name: SonarCloud

on:
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt  # Asegúrate de tener un archivo requirements.txt con tus dependencias

      - name: Run tests and coverage
        run: |
          coverage run manage.py test  # Ejecuta tus pruebas y mide la cobertura con Coverage.py
          coverage xml -o coverage.xml  # Genera un informe en formato XML para SonarCloud
          
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
